export const PORTFOLIO_DATA = {
  profile: {
    name: "Ansarul Khan",
    title: "Student | AI Automation Learner | Web Developer",
    roles: ["Web Developer", "AI Automation Learner", "Student at Chandigarh University", "Freelance Developer"],
    about: "I am Ansarul Khan, a student from Nepal currently studying BCA at Chandigarh University, India. I enjoy building modern websites and web applications and turning ideas into useful digital solutions. I am also trying freelancing to gain real-world experience. I am always learning new technologies and improving my skills to grow as a developer and AI automation learner.",
    email: "anshar22khan@gmail.com",
    linkedIn: "https://www.linkedin.com/in/ansarul-rain-7a325b34b/",
    github: "https://github.com/ansukhan164-rgb",
    resume: "#", // Placeholder
  },
  skills: {
    engineering: [
      { name: "HTML", icon: "html" },
      { name: "CSS", icon: "css" },
      { name: "JavaScript", icon: "js" },
      { name: "React", icon: "react" },
      { name: "Responsive Design", icon: "layout" },
    ],
    neural: [
      { name: "AI Automation Basics", icon: "cpu" },
      { name: "Python", icon: "py" },
      { name: "Git & GitHub", icon: "git" },
    ],
    cognitive: [
      { name: "Problem Solving", icon: "brain" },
      { name: "Communication", icon: "message-square" },
      { name: "Teamwork", icon: "users" },
      { name: "Creativity", icon: "palette" },
    ],
    languages: ["C", "C++", "Java"],
  },
  projects: [
    {
      title: "AlphaX Chat",
      description: "A full-stack real-time messaging app with real-time capabilities and a sleek interface.",
      tech: ["MongoDB", "Express", "React", "Node.js"],
      link: "https://github.com/ansukhan164-rgb/Advanced-Web-Dev-Mini-Project-using-MERN",
      category: "Web",
      featured: true,
    },
    {
      title: "AstraVision",
      description: "Advanced real-time hand tracking and gesture-based interactive system for human-computer interaction.",
      tech: ["Python", "OpenCV", "MediaPipe", "HTML/CSS"],
      link: "https://github.com/ansukhan164-rgb/AstraVision",
      category: "AI",
      featured: true,
    },
    {
      title: "Cyber-Scientific Calculator",
      description: "A futuristic Cyberpunk-style Scientific Calculator with advanced math functions.",
      tech: ["Java Swing", "AWT"],
      link: "https://github.com/ansukhan164-rgb/Scientific-Cal.-Java-Pr.-Mini-Project",
      category: "Tools",
      featured: false,
    },
    {
      title: "Bike Buyer Analysis",
      description: "Data science project analyzing bike buyer demographics using advanced Excel functions.",
      tech: ["Excel", "Data Analysis"],
      link: "https://github.com/ansukhan164-rgb/DS-using-Excel-Mini-Project",
      category: "Data Science",
      featured: false,
    },
    {
      title: "Nexus AI Chatbot",
      description: "A premium, production-grade AI chatbot interface with a modular Flask backend powered by Google Gemini 1.5 Flash for intelligent and natural interactions.",
      tech: ["Flask", "Google Gemini 1.5 Flash", "AI"],
      link: "https://github.com/ansukhan164-rgb/NEXUS-AI-Chatbot",
      category: "AI",
      featured: true,
    },
    {
      title: "ChakraAstra-Vision",
      description: "An advanced AI-powered vision platform utilizing Computer Vision and Machine Learning to process and interpret visual data instantly and visual intelligence to modern applications.",
      tech: ["Computer Vision", "Machine Learning", "AI"],
      link: "https://github.com/ansukhan164-rgb/ChakraAstra-Vision",
      category: "AI",
      featured: true,
    },
  ],
  experience: [
    {
      year: "2024 - Present",
      title: "BCA Student",
      organization: "Chandigarh University, India",
      description: "Studying Bachelor of Computer Applications, focusing on software development and AI foundations.",
      type: "Education",
    },
    {
      year: "Present",
      title: "Freelance Web Developer",
      organization: "Self-Employed",
      description: "Building modern web applications and digital solutions for clients, focusing on responsiveness and UX.",
      type: "Experience",
    },
  ],
};
